export const Channels = {
  RepoOpen: 'repo:open',
  RepoPick: 'repo:pick',
  RepoRecents: 'repo:recents',
  RepoRemoveRecent: 'repo:removeRecent',
  StatusGet: 'status:get',
  DiffFile: 'diff:file',
  StageAdd: 'stage:add',
  StageReset: 'stage:reset',
  CommitCreate: 'commit:create',
  RemoteFetch: 'remote:fetch',
  RemotePull: 'remote:pull',
  RemotePush: 'remote:push',
  BranchList: 'branch:list',
  BranchCheckout: 'branch:checkout',
  BranchCreate: 'branch:create',
  BranchCheckoutDetached: 'branch:checkoutDetached',
  BranchCreateFromCommit: 'branch:createFromCommit',
  BranchCheckoutRemote: 'branch:checkoutRemote',
  RefsList: 'refs:list',
  LogRecent: 'log:recent',
  LogGraph: 'log:graph',
  CommitShow: 'commit:show',
  CommitShowFileDiff: 'commit:showFileDiff',
  StashList: 'stash:list',
  StashPush: 'stash:push',
  StashPop: 'stash:pop',
  StashApply: 'stash:apply',
  StashDrop: 'stash:drop',
  StashFiles: 'stash:files',
  StashFileDiff: 'stash:fileDiff',
  StashApplyFile: 'stash:applyFile',
  WindowResize: 'window:resize',
  FileDiscard: 'file:discard',
  RepoGetLast: 'repo:getLast',
  BranchResetToRemote: 'branch:resetToRemote',
  TagCreate: 'tag:create',
  TagDelete: 'tag:delete',
  CommitCherryPick: 'commit:cherryPick',
  CommitRevert: 'commit:revert',
  CommitReset: 'commit:reset',
  ShellOpenPath: 'shell:openPath',
  ShellRevealInFolder: 'shell:revealInFolder',
  DryRunStatus: 'dryRun:status',
  // One-way pushes from main → renderer (no invoke, use ipcRenderer.on)
  MenuOpenRepo: 'menu:open-repo',
  MenuCloseRepo: 'menu:close-repo'
} as const

export type ChannelName = (typeof Channels)[keyof typeof Channels]
