export const Channels = {
  RepoOpen: 'repo:open',
  RepoPick: 'repo:pick',
  RepoRecents: 'repo:recents',
  RepoRemoveRecent: 'repo:removeRecent',
  StatusGet: 'status:get',
  DiffFile: 'diff:file',
  StageAdd: 'stage:add',
  StageReset: 'stage:reset',
  HunkStage: 'hunk:stage',
  HunkUnstage: 'hunk:unstage',
  HunkDiscard: 'hunk:discard',
  CommitCreate: 'commit:create',
  RemoteFetch: 'remote:fetch',
  RemotePull: 'remote:pull',
  RemotePush: 'remote:push',
  BranchList: 'branch:list',
  BranchCheckout: 'branch:checkout',
  BranchCreate: 'branch:create',
  BranchCheckoutDetached: 'branch:checkoutDetached',
  BranchCreateFromCommit: 'branch:createFromCommit',
  BranchCheckoutRemote: 'branch:checkoutRemote',
  BranchDelete: 'branch:delete',
  RefsList: 'refs:list',
  LogRecent: 'log:recent',
  LogGraph: 'log:graph',
  CommitShow: 'commit:show',
  CommitShowFileDiff: 'commit:showFileDiff',
  StashList: 'stash:list',
  StashPush: 'stash:push',
  StashPop: 'stash:pop',
  StashApply: 'stash:apply',
  StashDrop: 'stash:drop',
  StashFiles: 'stash:files',
  StashFileDiff: 'stash:fileDiff',
  StashApplyFile: 'stash:applyFile',
  WindowResize: 'window:resize',
  FileDiscard: 'file:discard',
  RepoGetLast: 'repo:getLast',
  BranchResetToRemote: 'branch:resetToRemote',
  BranchResetHard: 'branch:resetHard',
  TagCreate: 'tag:create',
  TagDelete: 'tag:delete',
  CommitCherryPick: 'commit:cherryPick',
  CommitRevert: 'commit:revert',
  CommitReset: 'commit:reset',
  ShellOpenPath: 'shell:openPath',
  ShellRevealInFolder: 'shell:revealInFolder',
  ShellOpenExternal: 'shell:openExternal',
  DryRunStatus: 'dryRun:status',
  PrList: 'pr:list',
  PrRerunRun: 'pr:rerunRun',
  PrRerunLatest: 'pr:rerunLatest',
  CiAvailable: 'ci:available',
  CiPrStatus: 'ci:prStatus',
  CiCommitChecks: 'ci:commitChecks',
  SettingsGet: 'settings:get',
  SettingsUpdate: 'settings:update',
  AiGenerateCommitMessage: 'ai:generateCommitMessage',
  // Git undo (reflog-based)
  GitUndo: 'git:undo',
  GitHeadSha: 'git:headSha',
  // .gitignore
  GitignoreRead: 'gitignore:read',
  GitignoreWrite: 'gitignore:write',
  GitignoreAppend: 'gitignore:append',
  // PR creation & review
  PrCreate: 'pr:create',
  PrReview: 'pr:review',
  PrDiff: 'pr:diff',
  // Conflict resolution
  ConflictVersions: 'conflict:versions',
  ConflictResolve: 'conflict:resolve',
  ConflictUseSide: 'conflict:useSide',
  MergeContinue: 'merge:continue',
  MergeAbort: 'merge:abort',
  // Interactive rebase
  RebaseStart: 'rebase:start',
  RebaseStatus: 'rebase:status',
  RebaseContinue: 'rebase:continue',
  RebaseAbort: 'rebase:abort',
  RebaseOnto: 'rebase:onto',
  // Log search
  LogSearch: 'log:search',
  // One-way pushes from main → renderer (no invoke, use ipcRenderer.on)
  MenuOpenRepo: 'menu:open-repo',
  MenuCloseRepo: 'menu:close-repo'
} as const

export type ChannelName = (typeof Channels)[keyof typeof Channels]
